/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { TransportType, TransportType$ } from "./transporttype";
import { z } from "zod";

export enum Status {
    Active = "active",
}

/**
 * Connection information to the default port.
 */
export type ActiveConnectionInfo = {
    host: string;
    port: number;
    /**
     * Unique identifier to a game session or match. Use the default system generated ID or overwrite it with your own.
     *
     * @remarks
     * Note: error will be returned if `roomId` is not globally unique.
     */
    roomId: string;
    status: Status;
    /**
     * Transport type specifies the underlying communication protocol to the exposed port.
     */
    transportType: TransportType;
};

/** @internal */
export const Status$ = z.nativeEnum(Status);

/** @internal */
export namespace ActiveConnectionInfo$ {
    export type Inbound = {
        host: string;
        port: number;
        roomId: string;
        status: Status;
        transportType: TransportType;
    };

    export const inboundSchema: z.ZodType<ActiveConnectionInfo, z.ZodTypeDef, Inbound> = z
        .object({
            host: z.string(),
            port: z.number(),
            roomId: z.string(),
            status: Status$,
            transportType: TransportType$,
        })
        .transform((v) => ({
            host: v.host,
            port: v.port,
            roomId: v.roomId,
            status: v.status,
            transportType: v.transportType,
        }));

    export type Outbound = {
        host: string;
        port: number;
        roomId: string;
        status: Status;
        transportType: TransportType;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ActiveConnectionInfo> = z
        .object({
            host: z.string(),
            port: z.number(),
            roomId: z.string(),
            status: Status$,
            transportType: TransportType$,
        })
        .transform((v) => ({
            host: v.host,
            port: v.port,
            roomId: v.roomId,
            status: v.status,
            transportType: v.transportType,
        }));
}
