/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { Region, Region$ } from "./region";
import { z } from "zod";

export type RegionalContainerTags = {
    containerTag: string;
    region: Region;
};

/**
 * Current status of your build.
 *
 * @remarks
 *
 * `created`: a build was created but not yet run
 *
 * `running`: the build process is actively executing
 *
 * `succeeded`: the game server artifact was successfully built and stored in the Hathora registries
 *
 * `failed`: the build process was unsuccessful, most likely due to an error with the `Dockerfile`
 */
export enum BuildStatus {
    Created = "created",
    Running = "running",
    Succeeded = "succeeded",
    Failed = "failed",
}

/**
 * A build represents a game server artifact and its associated metadata.
 */
export type Build = {
    /**
     * System generated unique identifier for an application.
     */
    appId: string;
    /**
     * System generated id for a build. Increments by 1.
     */
    buildId: number;
    buildTag: string | null;
    /**
     * When [`CreateBuild()`](https://hathora.dev/api#tag/BuildV1/operation/CreateBuild) is called.
     */
    createdAt: Date;
    /**
     * Email address for the user that created the build.
     */
    createdBy: string;
    /**
     * When the build was deleted.
     */
    deletedAt: Date | null;
    /**
     * When [`RunBuild()`](https://hathora.dev/api#tag/BuildV1/operation/RunBuild) finished executing.
     */
    finishedAt: Date | null;
    /**
     * The size (in bytes) of the Docker image built by Hathora.
     */
    imageSize: number;
    /**
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    regionalContainerTags: Array<RegionalContainerTags>;
    /**
     * When [`RunBuild()`](https://hathora.dev/api#tag/BuildV1/operation/RunBuild) is called.
     */
    startedAt: Date | null;
    /**
     * Current status of your build.
     *
     * @remarks
     *
     * `created`: a build was created but not yet run
     *
     * `running`: the build process is actively executing
     *
     * `succeeded`: the game server artifact was successfully built and stored in the Hathora registries
     *
     * `failed`: the build process was unsuccessful, most likely due to an error with the `Dockerfile`
     */
    status: BuildStatus;
};

/** @internal */
export namespace RegionalContainerTags$ {
    export type Inbound = {
        containerTag: string;
        region: Region;
    };

    export const inboundSchema: z.ZodType<RegionalContainerTags, z.ZodTypeDef, Inbound> = z
        .object({
            containerTag: z.string(),
            region: Region$,
        })
        .transform((v) => ({
            containerTag: v.containerTag,
            region: v.region,
        }));

    export type Outbound = {
        containerTag: string;
        region: Region;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RegionalContainerTags> = z
        .object({
            containerTag: z.string(),
            region: Region$,
        })
        .transform((v) => ({
            containerTag: v.containerTag,
            region: v.region,
        }));
}

/** @internal */
export const BuildStatus$ = z.nativeEnum(BuildStatus);

/** @internal */
export namespace Build$ {
    export type Inbound = {
        appId: string;
        buildId: number;
        buildTag: string | null;
        createdAt: string;
        createdBy: string;
        deletedAt: string | null;
        finishedAt: string | null;
        imageSize: number;
        regionalContainerTags: Array<RegionalContainerTags$.Inbound>;
        startedAt: string | null;
        status: BuildStatus;
    };

    export const inboundSchema: z.ZodType<Build, z.ZodTypeDef, Inbound> = z
        .object({
            appId: z.string(),
            buildId: z.number().int(),
            buildTag: z.string().nullable(),
            createdAt: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v)),
            createdBy: z.string(),
            deletedAt: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v))
                .nullable(),
            finishedAt: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v))
                .nullable(),
            imageSize: z.number(),
            regionalContainerTags: z.array(z.lazy(() => RegionalContainerTags$.inboundSchema)),
            startedAt: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v))
                .nullable(),
            status: BuildStatus$,
        })
        .transform((v) => ({
            appId: v.appId,
            buildId: v.buildId,
            buildTag: v.buildTag,
            createdAt: v.createdAt,
            createdBy: v.createdBy,
            deletedAt: v.deletedAt,
            finishedAt: v.finishedAt,
            imageSize: v.imageSize,
            regionalContainerTags: v.regionalContainerTags,
            startedAt: v.startedAt,
            status: v.status,
        }));

    export type Outbound = {
        appId: string;
        buildId: number;
        buildTag: string | null;
        createdAt: string;
        createdBy: string;
        deletedAt: string | null;
        finishedAt: string | null;
        imageSize: number;
        regionalContainerTags: Array<RegionalContainerTags$.Outbound>;
        startedAt: string | null;
        status: BuildStatus;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Build> = z
        .object({
            appId: z.string(),
            buildId: z.number().int(),
            buildTag: z.string().nullable(),
            createdAt: z.date().transform((v) => v.toISOString()),
            createdBy: z.string(),
            deletedAt: z
                .date()
                .transform((v) => v.toISOString())
                .nullable(),
            finishedAt: z
                .date()
                .transform((v) => v.toISOString())
                .nullable(),
            imageSize: z.number(),
            regionalContainerTags: z.array(z.lazy(() => RegionalContainerTags$.outboundSchema)),
            startedAt: z
                .date()
                .transform((v) => v.toISOString())
                .nullable(),
            status: BuildStatus$,
        })
        .transform((v) => ({
            appId: v.appId,
            buildId: v.buildId,
            buildTag: v.buildTag,
            createdAt: v.createdAt,
            createdBy: v.createdBy,
            deletedAt: v.deletedAt,
            finishedAt: v.finishedAt,
            imageSize: v.imageSize,
            regionalContainerTags: v.regionalContainerTags,
            startedAt: v.startedAt,
            status: v.status,
        }));
}
