/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export enum CardBrand {
    Amex = "amex",
    CartesBancaires = "cartes_bancaires",
    Diners = "diners",
    Discover = "discover",
    Jcb = "jcb",
    Mastercard = "mastercard",
    Visa = "visa",
    Unionpay = "unionpay",
    Card = "card",
}

/** @internal */
export const CardBrand$ = z.nativeEnum(CardBrand);
