/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ExposedPort, ExposedPort$ } from "./exposedport";
import { z } from "zod";

/**
 * `exposedPort` will only be available when the `status` of a room is "active".
 */
export enum ConnectionInfoV2Status {
    Starting = "starting",
    Active = "active",
}

/**
 * Connection information for the default and additional ports.
 */
export type ConnectionInfoV2 = {
    additionalExposedPorts: Array<ExposedPort>;
    /**
     * Connection details for an active process.
     */
    exposedPort?: ExposedPort | undefined;
    /**
     * Unique identifier to a game session or match. Use the default system generated ID or overwrite it with your own.
     *
     * @remarks
     * Note: error will be returned if `roomId` is not globally unique.
     */
    roomId: string;
    /**
     * `exposedPort` will only be available when the `status` of a room is "active".
     */
    status: ConnectionInfoV2Status;
};

/** @internal */
export const ConnectionInfoV2Status$ = z.nativeEnum(ConnectionInfoV2Status);

/** @internal */
export namespace ConnectionInfoV2$ {
    export type Inbound = {
        additionalExposedPorts: Array<ExposedPort$.Inbound>;
        exposedPort?: ExposedPort$.Inbound | undefined;
        roomId: string;
        status: ConnectionInfoV2Status;
    };

    export const inboundSchema: z.ZodType<ConnectionInfoV2, z.ZodTypeDef, Inbound> = z
        .object({
            additionalExposedPorts: z.array(ExposedPort$.inboundSchema),
            exposedPort: ExposedPort$.inboundSchema.optional(),
            roomId: z.string(),
            status: ConnectionInfoV2Status$,
        })
        .transform((v) => ({
            additionalExposedPorts: v.additionalExposedPorts,
            ...(v.exposedPort === undefined ? null : { exposedPort: v.exposedPort }),
            roomId: v.roomId,
            status: v.status,
        }));

    export type Outbound = {
        additionalExposedPorts: Array<ExposedPort$.Outbound>;
        exposedPort?: ExposedPort$.Outbound | undefined;
        roomId: string;
        status: ConnectionInfoV2Status;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ConnectionInfoV2> = z
        .object({
            additionalExposedPorts: z.array(ExposedPort$.outboundSchema),
            exposedPort: ExposedPort$.outboundSchema.optional(),
            roomId: z.string(),
            status: ConnectionInfoV2Status$,
        })
        .transform((v) => ({
            additionalExposedPorts: v.additionalExposedPorts,
            ...(v.exposedPort === undefined ? null : { exposedPort: v.exposedPort }),
            roomId: v.roomId,
            status: v.status,
        }));
}
