/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { TransportType, TransportType$ } from "./transporttype";
import { z } from "zod";

/**
 * A container port object represents the transport configruations for how your server will listen.
 */
export type ContainerPort = {
    /**
     * Readable name for the port.
     */
    name: string;
    port: number;
    /**
     * Transport type specifies the underlying communication protocol to the exposed port.
     */
    transportType: TransportType;
};

/** @internal */
export namespace ContainerPort$ {
    export type Inbound = {
        name: string;
        port: number;
        transportType: TransportType;
    };

    export const inboundSchema: z.ZodType<ContainerPort, z.ZodTypeDef, Inbound> = z
        .object({
            name: z.string(),
            port: z.number().int(),
            transportType: TransportType$,
        })
        .transform((v) => ({
            name: v.name,
            port: v.port,
            transportType: v.transportType,
        }));

    export type Outbound = {
        name: string;
        port: number;
        transportType: TransportType;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ContainerPort> = z
        .object({
            name: z.string(),
            port: z.number().int(),
            transportType: TransportType$,
        })
        .transform((v) => ({
            name: v.name,
            port: v.port,
            transportType: v.transportType,
        }));
}
