/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ConnectionInfoV2, ConnectionInfoV2$ } from "./connectioninfov2";
import { CreateRoomParams, CreateRoomParams$ } from "./createroomparams";
import { z } from "zod";

export type CreateRoomRequest = {
    createRoomParams: CreateRoomParams;
    appId?: string | undefined;
    roomId?: string | undefined;
};

export type CreateRoomResponse = {
    connectionInfoV2?: ConnectionInfoV2 | undefined;
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace CreateRoomRequest$ {
    export type Inbound = {
        CreateRoomParams: CreateRoomParams$.Inbound;
        appId?: string | undefined;
        roomId?: string | undefined;
    };

    export const inboundSchema: z.ZodType<CreateRoomRequest, z.ZodTypeDef, Inbound> = z
        .object({
            CreateRoomParams: CreateRoomParams$.inboundSchema,
            appId: z.string().optional(),
            roomId: z.string().optional(),
        })
        .transform((v) => ({
            createRoomParams: v.CreateRoomParams,
            ...(v.appId === undefined ? null : { appId: v.appId }),
            ...(v.roomId === undefined ? null : { roomId: v.roomId }),
        }));

    export type Outbound = {
        CreateRoomParams: CreateRoomParams$.Outbound;
        appId?: string | undefined;
        roomId?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateRoomRequest> = z
        .object({
            createRoomParams: CreateRoomParams$.outboundSchema,
            appId: z.string().optional(),
            roomId: z.string().optional(),
        })
        .transform((v) => ({
            CreateRoomParams: v.createRoomParams,
            ...(v.appId === undefined ? null : { appId: v.appId }),
            ...(v.roomId === undefined ? null : { roomId: v.roomId }),
        }));
}

/** @internal */
export namespace CreateRoomResponse$ {
    export type Inbound = {
        ConnectionInfoV2?: ConnectionInfoV2$.Inbound | undefined;
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
    };

    export const inboundSchema: z.ZodType<CreateRoomResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ConnectionInfoV2: ConnectionInfoV2$.inboundSchema.optional(),
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => ({
            ...(v.ConnectionInfoV2 === undefined ? null : { connectionInfoV2: v.ConnectionInfoV2 }),
            contentType: v.ContentType,
            statusCode: v.StatusCode,
            rawResponse: v.RawResponse,
        }));

    export type Outbound = {
        ConnectionInfoV2?: ConnectionInfoV2$.Outbound | undefined;
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateRoomResponse> = z
        .object({
            connectionInfoV2: ConnectionInfoV2$.outboundSchema.optional(),
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => ({
            ...(v.connectionInfoV2 === undefined ? null : { ConnectionInfoV2: v.connectionInfoV2 }),
            ContentType: v.contentType,
            StatusCode: v.statusCode,
            RawResponse: v.rawResponse,
        }));
}
