/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { LobbyVisibility, LobbyVisibility$ } from "./lobbyvisibility";
import { Region, Region$ } from "./region";
import { z } from "zod";

export type CreateLobbyV3Params = {
    region: Region;
    /**
     * Optional configuration parameters for the room. Can be any string including stringified JSON. It is accessible from the room via [`GetRoomInfo()`](https://hathora.dev/api#tag/RoomV2/operation/GetRoomInfo).
     */
    roomConfig: string;
    /**
     * Types of lobbies a player can create.
     *
     * @remarks
     *
     * `private`: the player who created the room must share the roomId with their friends
     *
     * `public`: visible in the public lobby list, anyone can join
     *
     * `local`: for testing with a server running locally
     */
    visibility: LobbyVisibility;
};

/** @internal */
export namespace CreateLobbyV3Params$ {
    export type Inbound = {
        region: Region;
        roomConfig: string;
        visibility: LobbyVisibility;
    };

    export const inboundSchema: z.ZodType<CreateLobbyV3Params, z.ZodTypeDef, Inbound> = z
        .object({
            region: Region$,
            roomConfig: z.string(),
            visibility: LobbyVisibility$,
        })
        .transform((v) => ({
            region: v.region,
            roomConfig: v.roomConfig,
            visibility: v.visibility,
        }));

    export type Outbound = {
        region: Region;
        roomConfig: string;
        visibility: LobbyVisibility;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateLobbyV3Params> = z
        .object({
            region: Region$,
            roomConfig: z.string(),
            visibility: LobbyVisibility$,
        })
        .transform((v) => ({
            region: v.region,
            roomConfig: v.roomConfig,
            visibility: v.visibility,
        }));
}
