/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { CreateLobbyParams, CreateLobbyParams$ } from "./createlobbyparams";
import { Lobby, Lobby$ } from "./lobby";
import { z } from "zod";

export type CreateLobbyDeprecatedSecurity = {
    playerAuth: string;
};

export type CreateLobbyDeprecatedRequest = {
    createLobbyParams: CreateLobbyParams;
    appId?: string | undefined;
    roomId?: string | undefined;
};

export type CreateLobbyDeprecatedResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    lobby?: Lobby | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace CreateLobbyDeprecatedRequest$ {
    export type Inbound = {
        CreateLobbyParams: CreateLobbyParams$.Inbound;
        appId?: string | undefined;
        roomId?: string | undefined;
    };

    export const inboundSchema: z.ZodType<CreateLobbyDeprecatedRequest, z.ZodTypeDef, Inbound> = z
        .object({
            CreateLobbyParams: CreateLobbyParams$.inboundSchema,
            appId: z.string().optional(),
            roomId: z.string().optional(),
        })
        .transform((v) => ({
            createLobbyParams: v.CreateLobbyParams,
            ...(v.appId === undefined ? null : { appId: v.appId }),
            ...(v.roomId === undefined ? null : { roomId: v.roomId }),
        }));

    export type Outbound = {
        CreateLobbyParams: CreateLobbyParams$.Outbound;
        appId?: string | undefined;
        roomId?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateLobbyDeprecatedRequest> = z
        .object({
            createLobbyParams: CreateLobbyParams$.outboundSchema,
            appId: z.string().optional(),
            roomId: z.string().optional(),
        })
        .transform((v) => ({
            CreateLobbyParams: v.createLobbyParams,
            ...(v.appId === undefined ? null : { appId: v.appId }),
            ...(v.roomId === undefined ? null : { roomId: v.roomId }),
        }));
}

/** @internal */
export namespace CreateLobbyDeprecatedResponse$ {
    export type Inbound = {
        ContentType: string;
        Lobby?: Lobby$.Inbound | undefined;
        StatusCode: number;
        RawResponse: Response;
    };

    export const inboundSchema: z.ZodType<CreateLobbyDeprecatedResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            Lobby: Lobby$.inboundSchema.optional(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => ({
            contentType: v.ContentType,
            ...(v.Lobby === undefined ? null : { lobby: v.Lobby }),
            statusCode: v.StatusCode,
            rawResponse: v.RawResponse,
        }));

    export type Outbound = {
        ContentType: string;
        Lobby?: Lobby$.Outbound | undefined;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateLobbyDeprecatedResponse> =
        z
            .object({
                contentType: z.string(),
                lobby: Lobby$.outboundSchema.optional(),
                statusCode: z.number().int(),
                rawResponse: z.instanceof(Response).transform(() => {
                    throw new Error("Response cannot be serialized");
                }),
            })
            .transform((v) => ({
                ContentType: v.contentType,
                ...(v.lobby === undefined ? null : { Lobby: v.lobby }),
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            }));
}
