/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { LobbyInitialConfig, LobbyInitialConfig$ } from "./lobbyinitialconfig";
import { LobbyVisibility, LobbyVisibility$ } from "./lobbyvisibility";
import { Region, Region$ } from "./region";
import { z } from "zod";

export type CreateLobbyParams = {
    /**
     * User input to initialize the game state. Object must be smaller than 64KB.
     */
    initialConfig: LobbyInitialConfig;
    region: Region;
    /**
     * Types of lobbies a player can create.
     *
     * @remarks
     *
     * `private`: the player who created the room must share the roomId with their friends
     *
     * `public`: visible in the public lobby list, anyone can join
     *
     * `local`: for testing with a server running locally
     */
    visibility: LobbyVisibility;
};

/** @internal */
export namespace CreateLobbyParams$ {
    export type Inbound = {
        initialConfig: LobbyInitialConfig$.Inbound;
        region: Region;
        visibility: LobbyVisibility;
    };

    export const inboundSchema: z.ZodType<CreateLobbyParams, z.ZodTypeDef, Inbound> = z
        .object({
            initialConfig: LobbyInitialConfig$.inboundSchema,
            region: Region$,
            visibility: LobbyVisibility$,
        })
        .transform((v) => ({
            initialConfig: v.initialConfig,
            region: v.region,
            visibility: v.visibility,
        }));

    export type Outbound = {
        initialConfig: LobbyInitialConfig$.Outbound;
        region: Region;
        visibility: LobbyVisibility;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateLobbyParams> = z
        .object({
            initialConfig: LobbyInitialConfig$.outboundSchema,
            region: Region$,
            visibility: LobbyVisibility$,
        })
        .transform((v) => ({
            initialConfig: v.initialConfig,
            region: v.region,
            visibility: v.visibility,
        }));
}
