/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ContainerPort, ContainerPort$ } from "./containerport";
import { PlanName, PlanName$ } from "./planname";
import { z } from "zod";

export type Env = {
    name: string;
    value: string;
};

/**
 * @deprecated enum: This will be removed in a future release, please migrate away from it as soon as possible.
 */
export enum DeploymentTransportType {
    Tcp = "tcp",
    Udp = "udp",
    Tls = "tls",
}

/**
 * Deployment is a versioned configuration for a build that describes runtime behavior.
 */
export type Deployment = {
    /**
     * Additional ports your server listens on.
     */
    additionalContainerPorts: Array<ContainerPort>;
    /**
     * System generated unique identifier for an application.
     */
    appId: string;
    /**
     * System generated id for a build. Increments by 1.
     */
    buildId: number;
    /**
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    containerPort: number;
    /**
     * When the deployment was created.
     */
    createdAt: Date;
    /**
     * Email address for the user that created the deployment.
     */
    createdBy: string;
    /**
     * A container port object represents the transport configruations for how your server will listen.
     */
    defaultContainerPort: ContainerPort;
    /**
     * System generated id for a deployment. Increments by 1.
     */
    deploymentId: number;
    /**
     * The environment variable that our process will have access to at runtime.
     */
    env: Array<Env>;
    /**
     * A plan defines how much CPU and memory is required to run an instance of your game server.
     *
     * @remarks
     *
     * `tiny`: shared core, 1gb memory
     *
     * `small`: 1 core, 2gb memory
     *
     * `medium`: 2 core, 4gb memory
     *
     * `large`: 4 core, 8gb memory
     */
    planName: PlanName;
    /**
     * The number of cores allocated to your process.
     */
    requestedCPU: number;
    /**
     * The amount of memory allocated to your process.
     */
    requestedMemoryMB: number;
    /**
     * Governs how many [rooms](https://hathora.dev/docs/concepts/hathora-entities#room) can be scheduled in a process.
     */
    roomsPerProcess: number;
    /**
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    transportType: DeploymentTransportType;
};

/** @internal */
export namespace Env$ {
    export type Inbound = {
        name: string;
        value: string;
    };

    export const inboundSchema: z.ZodType<Env, z.ZodTypeDef, Inbound> = z
        .object({
            name: z.string(),
            value: z.string(),
        })
        .transform((v) => ({
            name: v.name,
            value: v.value,
        }));

    export type Outbound = {
        name: string;
        value: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Env> = z
        .object({
            name: z.string(),
            value: z.string(),
        })
        .transform((v) => ({
            name: v.name,
            value: v.value,
        }));
}

/** @internal */
export const DeploymentTransportType$ = z.nativeEnum(DeploymentTransportType);

/** @internal */
export namespace Deployment$ {
    export type Inbound = {
        additionalContainerPorts: Array<ContainerPort$.Inbound>;
        appId: string;
        buildId: number;
        containerPort: number;
        createdAt: string;
        createdBy: string;
        defaultContainerPort: ContainerPort$.Inbound;
        deploymentId: number;
        env: Array<Env$.Inbound>;
        planName: PlanName;
        requestedCPU: number;
        requestedMemoryMB: number;
        roomsPerProcess: number;
        transportType: DeploymentTransportType;
    };

    export const inboundSchema: z.ZodType<Deployment, z.ZodTypeDef, Inbound> = z
        .object({
            additionalContainerPorts: z.array(ContainerPort$.inboundSchema),
            appId: z.string(),
            buildId: z.number().int(),
            containerPort: z.number(),
            createdAt: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v)),
            createdBy: z.string(),
            defaultContainerPort: ContainerPort$.inboundSchema,
            deploymentId: z.number().int(),
            env: z.array(z.lazy(() => Env$.inboundSchema)),
            planName: PlanName$,
            requestedCPU: z.number(),
            requestedMemoryMB: z.number(),
            roomsPerProcess: z.number().int(),
            transportType: DeploymentTransportType$,
        })
        .transform((v) => ({
            additionalContainerPorts: v.additionalContainerPorts,
            appId: v.appId,
            buildId: v.buildId,
            containerPort: v.containerPort,
            createdAt: v.createdAt,
            createdBy: v.createdBy,
            defaultContainerPort: v.defaultContainerPort,
            deploymentId: v.deploymentId,
            env: v.env,
            planName: v.planName,
            requestedCPU: v.requestedCPU,
            requestedMemoryMB: v.requestedMemoryMB,
            roomsPerProcess: v.roomsPerProcess,
            transportType: v.transportType,
        }));

    export type Outbound = {
        additionalContainerPorts: Array<ContainerPort$.Outbound>;
        appId: string;
        buildId: number;
        containerPort: number;
        createdAt: string;
        createdBy: string;
        defaultContainerPort: ContainerPort$.Outbound;
        deploymentId: number;
        env: Array<Env$.Outbound>;
        planName: PlanName;
        requestedCPU: number;
        requestedMemoryMB: number;
        roomsPerProcess: number;
        transportType: DeploymentTransportType;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Deployment> = z
        .object({
            additionalContainerPorts: z.array(ContainerPort$.outboundSchema),
            appId: z.string(),
            buildId: z.number().int(),
            containerPort: z.number(),
            createdAt: z.date().transform((v) => v.toISOString()),
            createdBy: z.string(),
            defaultContainerPort: ContainerPort$.outboundSchema,
            deploymentId: z.number().int(),
            env: z.array(z.lazy(() => Env$.outboundSchema)),
            planName: PlanName$,
            requestedCPU: z.number(),
            requestedMemoryMB: z.number(),
            roomsPerProcess: z.number().int(),
            transportType: DeploymentTransportType$,
        })
        .transform((v) => ({
            additionalContainerPorts: v.additionalContainerPorts,
            appId: v.appId,
            buildId: v.buildId,
            containerPort: v.containerPort,
            createdAt: v.createdAt,
            createdBy: v.createdBy,
            defaultContainerPort: v.defaultContainerPort,
            deploymentId: v.deploymentId,
            env: v.env,
            planName: v.planName,
            requestedCPU: v.requestedCPU,
            requestedMemoryMB: v.requestedMemoryMB,
            roomsPerProcess: v.roomsPerProcess,
            transportType: v.transportType,
        }));
}
