/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { LobbyV3, LobbyV3$ } from "./lobbyv3";
import { z } from "zod";

export type GetLobbyInfoByRoomIdRequest = {
    roomId: string;
    appId?: string | undefined;
};

export type GetLobbyInfoByRoomIdResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * Ok
     */
    lobbyV3?: LobbyV3 | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace GetLobbyInfoByRoomIdRequest$ {
    export type Inbound = {
        roomId: string;
        appId?: string | undefined;
    };

    export const inboundSchema: z.ZodType<GetLobbyInfoByRoomIdRequest, z.ZodTypeDef, Inbound> = z
        .object({
            roomId: z.string(),
            appId: z.string().optional(),
        })
        .transform((v) => ({
            roomId: v.roomId,
            ...(v.appId === undefined ? null : { appId: v.appId }),
        }));

    export type Outbound = {
        roomId: string;
        appId?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetLobbyInfoByRoomIdRequest> = z
        .object({
            roomId: z.string(),
            appId: z.string().optional(),
        })
        .transform((v) => ({
            roomId: v.roomId,
            ...(v.appId === undefined ? null : { appId: v.appId }),
        }));
}

/** @internal */
export namespace GetLobbyInfoByRoomIdResponse$ {
    export type Inbound = {
        ContentType: string;
        LobbyV3?: LobbyV3$.Inbound | undefined;
        StatusCode: number;
        RawResponse: Response;
    };

    export const inboundSchema: z.ZodType<GetLobbyInfoByRoomIdResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            LobbyV3: LobbyV3$.inboundSchema.optional(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => ({
            contentType: v.ContentType,
            ...(v.LobbyV3 === undefined ? null : { lobbyV3: v.LobbyV3 }),
            statusCode: v.StatusCode,
            rawResponse: v.RawResponse,
        }));

    export type Outbound = {
        ContentType: string;
        LobbyV3?: LobbyV3$.Outbound | undefined;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetLobbyInfoByRoomIdResponse> = z
        .object({
            contentType: z.string(),
            lobbyV3: LobbyV3$.outboundSchema.optional(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => ({
            ContentType: v.contentType,
            ...(v.lobbyV3 === undefined ? null : { LobbyV3: v.lobbyV3 }),
            StatusCode: v.statusCode,
            RawResponse: v.rawResponse,
        }));
}
