/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { PaymentMethod, PaymentMethod$ } from "./paymentmethod";
import { z } from "zod";

export type GetPaymentMethodResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * Ok
     */
    paymentMethod?: PaymentMethod | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace GetPaymentMethodResponse$ {
    export type Inbound = {
        ContentType: string;
        PaymentMethod?: PaymentMethod$.Inbound | undefined;
        StatusCode: number;
        RawResponse: Response;
    };

    export const inboundSchema: z.ZodType<GetPaymentMethodResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            PaymentMethod: PaymentMethod$.inboundSchema.optional(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => ({
            contentType: v.ContentType,
            ...(v.PaymentMethod === undefined ? null : { paymentMethod: v.PaymentMethod }),
            statusCode: v.StatusCode,
            rawResponse: v.RawResponse,
        }));

    export type Outbound = {
        ContentType: string;
        PaymentMethod?: PaymentMethod$.Outbound | undefined;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetPaymentMethodResponse> = z
        .object({
            contentType: z.string(),
            paymentMethod: PaymentMethod$.outboundSchema.optional(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => ({
            ContentType: v.contentType,
            ...(v.paymentMethod === undefined ? null : { PaymentMethod: v.paymentMethod }),
            StatusCode: v.statusCode,
            RawResponse: v.rawResponse,
        }));
}
