/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { LobbyV3, LobbyV3$ } from "./lobbyv3";
import { Region, Region$ } from "./region";
import { z } from "zod";

export type ListActivePublicLobbiesRequest = {
    appId?: string | undefined;
    /**
     * If omitted, active public lobbies in all regions will be returned.
     */
    region?: Region | undefined;
};

export type ListActivePublicLobbiesResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Ok
     */
    classes?: Array<LobbyV3> | undefined;
};

/** @internal */
export namespace ListActivePublicLobbiesRequest$ {
    export type Inbound = {
        appId?: string | undefined;
        region?: Region | undefined;
    };

    export const inboundSchema: z.ZodType<ListActivePublicLobbiesRequest, z.ZodTypeDef, Inbound> = z
        .object({
            appId: z.string().optional(),
            region: Region$.optional(),
        })
        .transform((v) => ({
            ...(v.appId === undefined ? null : { appId: v.appId }),
            ...(v.region === undefined ? null : { region: v.region }),
        }));

    export type Outbound = {
        appId?: string | undefined;
        region?: Region | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListActivePublicLobbiesRequest> =
        z
            .object({
                appId: z.string().optional(),
                region: Region$.optional(),
            })
            .transform((v) => ({
                ...(v.appId === undefined ? null : { appId: v.appId }),
                ...(v.region === undefined ? null : { region: v.region }),
            }));
}

/** @internal */
export namespace ListActivePublicLobbiesResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        classes?: Array<LobbyV3$.Inbound> | undefined;
    };

    export const inboundSchema: z.ZodType<ListActivePublicLobbiesResponse, z.ZodTypeDef, Inbound> =
        z
            .object({
                ContentType: z.string(),
                StatusCode: z.number().int(),
                RawResponse: z.instanceof(Response),
                classes: z.array(LobbyV3$.inboundSchema).optional(),
            })
            .transform((v) => ({
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.classes === undefined ? null : { classes: v.classes }),
            }));

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        classes?: Array<LobbyV3$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        ListActivePublicLobbiesResponse
    > = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            classes: z.array(LobbyV3$.outboundSchema).optional(),
        })
        .transform((v) => ({
            ContentType: v.contentType,
            StatusCode: v.statusCode,
            RawResponse: v.rawResponse,
            ...(v.classes === undefined ? null : { classes: v.classes }),
        }));
}
