/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { LobbyVisibility, LobbyVisibility$ } from "./lobbyvisibility";
import { Region, Region$ } from "./region";
import { z } from "zod";

/**
 * A lobby object allows you to store and manage metadata for your rooms.
 */
export type LobbyV3 = {
    /**
     * System generated unique identifier for an application.
     */
    appId: string;
    /**
     * When the lobby was created.
     */
    createdAt: Date;
    /**
     * Email address for the user that created the lobby.
     */
    createdBy: string;
    region: Region;
    roomConfig: string | null;
    /**
     * Unique identifier to a game session or match. Use the default system generated ID or overwrite it with your own.
     *
     * @remarks
     * Note: error will be returned if `roomId` is not globally unique.
     */
    roomId: string;
    /**
     * User-defined identifier for a lobby.
     */
    shortCode: string;
    /**
     * Types of lobbies a player can create.
     *
     * @remarks
     *
     * `private`: the player who created the room must share the roomId with their friends
     *
     * `public`: visible in the public lobby list, anyone can join
     *
     * `local`: for testing with a server running locally
     */
    visibility: LobbyVisibility;
};

/** @internal */
export namespace LobbyV3$ {
    export type Inbound = {
        appId: string;
        createdAt: string;
        createdBy: string;
        region: Region;
        roomConfig: string | null;
        roomId: string;
        shortCode: string;
        visibility: LobbyVisibility;
    };

    export const inboundSchema: z.ZodType<LobbyV3, z.ZodTypeDef, Inbound> = z
        .object({
            appId: z.string(),
            createdAt: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v)),
            createdBy: z.string(),
            region: Region$,
            roomConfig: z.string().nullable(),
            roomId: z.string(),
            shortCode: z.string(),
            visibility: LobbyVisibility$,
        })
        .transform((v) => ({
            appId: v.appId,
            createdAt: v.createdAt,
            createdBy: v.createdBy,
            region: v.region,
            roomConfig: v.roomConfig,
            roomId: v.roomId,
            shortCode: v.shortCode,
            visibility: v.visibility,
        }));

    export type Outbound = {
        appId: string;
        createdAt: string;
        createdBy: string;
        region: Region;
        roomConfig: string | null;
        roomId: string;
        shortCode: string;
        visibility: LobbyVisibility;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, LobbyV3> = z
        .object({
            appId: z.string(),
            createdAt: z.date().transform((v) => v.toISOString()),
            createdBy: z.string(),
            region: Region$,
            roomConfig: z.string().nullable(),
            roomId: z.string(),
            shortCode: z.string(),
            visibility: LobbyVisibility$,
        })
        .transform((v) => ({
            appId: v.appId,
            createdAt: v.createdAt,
            createdBy: v.createdBy,
            region: v.region,
            roomConfig: v.roomConfig,
            roomId: v.roomId,
            shortCode: v.shortCode,
            visibility: v.visibility,
        }));
}
