/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { LoginResponse, LoginResponse$ } from "./loginresponse";
import { z } from "zod";

export type LoginAnonymousRequest = {
    appId?: string | undefined;
};

export type LoginAnonymousResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * Ok
     */
    loginResponse?: LoginResponse | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace LoginAnonymousRequest$ {
    export type Inbound = {
        appId?: string | undefined;
    };

    export const inboundSchema: z.ZodType<LoginAnonymousRequest, z.ZodTypeDef, Inbound> = z
        .object({
            appId: z.string().optional(),
        })
        .transform((v) => ({
            ...(v.appId === undefined ? null : { appId: v.appId }),
        }));

    export type Outbound = {
        appId?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, LoginAnonymousRequest> = z
        .object({
            appId: z.string().optional(),
        })
        .transform((v) => ({
            ...(v.appId === undefined ? null : { appId: v.appId }),
        }));
}

/** @internal */
export namespace LoginAnonymousResponse$ {
    export type Inbound = {
        ContentType: string;
        LoginResponse?: LoginResponse$.Inbound | undefined;
        StatusCode: number;
        RawResponse: Response;
    };

    export const inboundSchema: z.ZodType<LoginAnonymousResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            LoginResponse: LoginResponse$.inboundSchema.optional(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => ({
            contentType: v.ContentType,
            ...(v.LoginResponse === undefined ? null : { loginResponse: v.LoginResponse }),
            statusCode: v.StatusCode,
            rawResponse: v.RawResponse,
        }));

    export type Outbound = {
        ContentType: string;
        LoginResponse?: LoginResponse$.Outbound | undefined;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, LoginAnonymousResponse> = z
        .object({
            contentType: z.string(),
            loginResponse: LoginResponse$.outboundSchema.optional(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => ({
            ContentType: v.contentType,
            ...(v.loginResponse === undefined ? null : { LoginResponse: v.loginResponse }),
            StatusCode: v.statusCode,
            RawResponse: v.rawResponse,
        }));
}
