/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type MetricValue = {
    timestamp: number;
    value: number;
};

/** @internal */
export namespace MetricValue$ {
    export type Inbound = {
        timestamp: number;
        value: number;
    };

    export const inboundSchema: z.ZodType<MetricValue, z.ZodTypeDef, Inbound> = z
        .object({
            timestamp: z.number(),
            value: z.number(),
        })
        .transform((v) => ({
            timestamp: v.timestamp,
            value: v.value,
        }));

    export type Outbound = {
        timestamp: number;
        value: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, MetricValue> = z
        .object({
            timestamp: z.number(),
            value: z.number(),
        })
        .transform((v) => ({
            timestamp: v.timestamp,
            value: v.value,
        }));
}
