/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { RoomStatus, RoomStatus$ } from "./roomstatus";
import { z } from "zod";

/**
 * Metadata on an allocated instance of a room.
 */
export type RoomWithoutAllocationsCurrentAllocation = {
    /**
     * System generated unique identifier to a runtime instance of your game server.
     */
    processId: string;
    /**
     * System generated unique identifier to an allocated instance of a room.
     */
    roomAllocationId: string;
    scheduledAt: Date;
    unscheduledAt: Date | null;
};

/**
 * From T, pick a set of properties whose keys are in the union K
 */
export type RoomWithoutAllocations = {
    /**
     * System generated unique identifier for an application.
     */
    appId: string;
    currentAllocation: RoomWithoutAllocationsCurrentAllocation | null;
    roomConfig: string | null;
    /**
     * Unique identifier to a game session or match. Use the default system generated ID or overwrite it with your own.
     *
     * @remarks
     * Note: error will be returned if `roomId` is not globally unique.
     */
    roomId: string;
    /**
     * The allocation status of a room.
     *
     * @remarks
     *
     * `scheduling`: a process is not allocated yet and the room is waiting to be scheduled
     *
     * `active`: ready to accept connections
     *
     * `suspended`: room is unallocated from the process but can be rescheduled later with the same `roomId`
     *
     * `destroyed`: all associated metadata is deleted
     */
    status: RoomStatus;
};

/** @internal */
export namespace RoomWithoutAllocationsCurrentAllocation$ {
    export type Inbound = {
        processId: string;
        roomAllocationId: string;
        scheduledAt: string;
        unscheduledAt: string | null;
    };

    export const inboundSchema: z.ZodType<
        RoomWithoutAllocationsCurrentAllocation,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            processId: z.string(),
            roomAllocationId: z.string(),
            scheduledAt: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v)),
            unscheduledAt: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v))
                .nullable(),
        })
        .transform((v) => ({
            processId: v.processId,
            roomAllocationId: v.roomAllocationId,
            scheduledAt: v.scheduledAt,
            unscheduledAt: v.unscheduledAt,
        }));

    export type Outbound = {
        processId: string;
        roomAllocationId: string;
        scheduledAt: string;
        unscheduledAt: string | null;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        RoomWithoutAllocationsCurrentAllocation
    > = z
        .object({
            processId: z.string(),
            roomAllocationId: z.string(),
            scheduledAt: z.date().transform((v) => v.toISOString()),
            unscheduledAt: z
                .date()
                .transform((v) => v.toISOString())
                .nullable(),
        })
        .transform((v) => ({
            processId: v.processId,
            roomAllocationId: v.roomAllocationId,
            scheduledAt: v.scheduledAt,
            unscheduledAt: v.unscheduledAt,
        }));
}

/** @internal */
export namespace RoomWithoutAllocations$ {
    export type Inbound = {
        appId: string;
        currentAllocation: RoomWithoutAllocationsCurrentAllocation$.Inbound | null;
        roomConfig: string | null;
        roomId: string;
        status: RoomStatus;
    };

    export const inboundSchema: z.ZodType<RoomWithoutAllocations, z.ZodTypeDef, Inbound> = z
        .object({
            appId: z.string(),
            currentAllocation: z
                .lazy(() => RoomWithoutAllocationsCurrentAllocation$.inboundSchema)
                .nullable(),
            roomConfig: z.string().nullable(),
            roomId: z.string(),
            status: RoomStatus$,
        })
        .transform((v) => ({
            appId: v.appId,
            currentAllocation: v.currentAllocation,
            roomConfig: v.roomConfig,
            roomId: v.roomId,
            status: v.status,
        }));

    export type Outbound = {
        appId: string;
        currentAllocation: RoomWithoutAllocationsCurrentAllocation$.Outbound | null;
        roomConfig: string | null;
        roomId: string;
        status: RoomStatus;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RoomWithoutAllocations> = z
        .object({
            appId: z.string(),
            currentAllocation: z
                .lazy(() => RoomWithoutAllocationsCurrentAllocation$.outboundSchema)
                .nullable(),
            roomConfig: z.string().nullable(),
            roomId: z.string(),
            status: RoomStatus$,
        })
        .transform((v) => ({
            appId: v.appId,
            currentAllocation: v.currentAllocation,
            roomConfig: v.roomConfig,
            roomId: v.roomId,
            status: v.status,
        }));
}
