/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as b64$ from "../lib/base64";
import { z } from "zod";

export type File = {
    content: Uint8Array | string;
    fileName: string;
};

export type RunBuildRequestBody = {
    file: File;
};

export type RunBuildRequest = {
    requestBody: RunBuildRequestBody;
    buildId: number;
    appId?: string | undefined;
};

export type RunBuildResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Ok
     */
    stream?: ReadableStream<Uint8Array> | undefined;
};

/** @internal */
export namespace File$ {
    export type Inbound = {
        content: Uint8Array | string;
        fileName: string;
    };

    export const inboundSchema: z.ZodType<File, z.ZodTypeDef, Inbound> = z
        .object({
            content: b64$.zodInbound,
            fileName: z.string(),
        })
        .transform((v) => ({
            content: v.content,
            fileName: v.fileName,
        }));

    export type Outbound = {
        content: Uint8Array;
        fileName: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, File> = z
        .object({
            content: b64$.zodOutbound,
            fileName: z.string(),
        })
        .transform((v) => ({
            content: v.content,
            fileName: v.fileName,
        }));
}

/** @internal */
export namespace RunBuildRequestBody$ {
    export type Inbound = {
        file: File$.Inbound;
    };

    export const inboundSchema: z.ZodType<RunBuildRequestBody, z.ZodTypeDef, Inbound> = z
        .object({
            file: z.lazy(() => File$.inboundSchema),
        })
        .transform((v) => ({
            file: v.file,
        }));

    export type Outbound = {
        file: File$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RunBuildRequestBody> = z
        .object({
            file: z.lazy(() => File$.outboundSchema),
        })
        .transform((v) => ({
            file: v.file,
        }));
}

/** @internal */
export namespace RunBuildRequest$ {
    export type Inbound = {
        RequestBody: RunBuildRequestBody$.Inbound;
        buildId: number;
        appId?: string | undefined;
    };

    export const inboundSchema: z.ZodType<RunBuildRequest, z.ZodTypeDef, Inbound> = z
        .object({
            RequestBody: z.lazy(() => RunBuildRequestBody$.inboundSchema),
            buildId: z.number().int(),
            appId: z.string().optional(),
        })
        .transform((v) => ({
            requestBody: v.RequestBody,
            buildId: v.buildId,
            ...(v.appId === undefined ? null : { appId: v.appId }),
        }));

    export type Outbound = {
        RequestBody: RunBuildRequestBody$.Outbound;
        buildId: number;
        appId?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RunBuildRequest> = z
        .object({
            requestBody: z.lazy(() => RunBuildRequestBody$.outboundSchema),
            buildId: z.number().int(),
            appId: z.string().optional(),
        })
        .transform((v) => ({
            RequestBody: v.requestBody,
            buildId: v.buildId,
            ...(v.appId === undefined ? null : { appId: v.appId }),
        }));
}

/** @internal */
export namespace RunBuildResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        stream?: ReadableStream<Uint8Array> | undefined;
    };

    export const inboundSchema: z.ZodType<RunBuildResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            stream: z.instanceof(ReadableStream<Uint8Array>).optional(),
        })
        .transform((v) => ({
            contentType: v.ContentType,
            statusCode: v.StatusCode,
            rawResponse: v.RawResponse,
            ...(v.stream === undefined ? null : { stream: v.stream }),
        }));

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        stream?: ReadableStream<Uint8Array> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RunBuildResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            stream: z.instanceof(ReadableStream<Uint8Array>).optional(),
        })
        .transform((v) => ({
            ContentType: v.contentType,
            StatusCode: v.statusCode,
            RawResponse: v.rawResponse,
            ...(v.stream === undefined ? null : { stream: v.stream }),
        }));
}
