/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { AppConfig, AppConfig$ } from "./appconfig";
import { Application, Application$ } from "./application";
import { z } from "zod";

export type UpdateAppRequest = {
    appConfig: AppConfig;
    appId?: string | undefined;
};

export type UpdateAppResponse = {
    /**
     * Ok
     */
    application?: Application | undefined;
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace UpdateAppRequest$ {
    export type Inbound = {
        AppConfig: AppConfig$.Inbound;
        appId?: string | undefined;
    };

    export const inboundSchema: z.ZodType<UpdateAppRequest, z.ZodTypeDef, Inbound> = z
        .object({
            AppConfig: AppConfig$.inboundSchema,
            appId: z.string().optional(),
        })
        .transform((v) => ({
            appConfig: v.AppConfig,
            ...(v.appId === undefined ? null : { appId: v.appId }),
        }));

    export type Outbound = {
        AppConfig: AppConfig$.Outbound;
        appId?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateAppRequest> = z
        .object({
            appConfig: AppConfig$.outboundSchema,
            appId: z.string().optional(),
        })
        .transform((v) => ({
            AppConfig: v.appConfig,
            ...(v.appId === undefined ? null : { appId: v.appId }),
        }));
}

/** @internal */
export namespace UpdateAppResponse$ {
    export type Inbound = {
        Application?: Application$.Inbound | undefined;
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
    };

    export const inboundSchema: z.ZodType<UpdateAppResponse, z.ZodTypeDef, Inbound> = z
        .object({
            Application: Application$.inboundSchema.optional(),
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => ({
            ...(v.Application === undefined ? null : { application: v.Application }),
            contentType: v.ContentType,
            statusCode: v.StatusCode,
            rawResponse: v.RawResponse,
        }));

    export type Outbound = {
        Application?: Application$.Outbound | undefined;
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateAppResponse> = z
        .object({
            application: Application$.outboundSchema.optional(),
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => ({
            ...(v.application === undefined ? null : { Application: v.application }),
            ContentType: v.contentType,
            StatusCode: v.statusCode,
            RawResponse: v.rawResponse,
        }));
}
