/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { UpdateRoomConfigParams, UpdateRoomConfigParams$ } from "./updateroomconfigparams";
import { z } from "zod";

export type UpdateRoomConfigRequest = {
    updateRoomConfigParams: UpdateRoomConfigParams;
    roomId: string;
    appId?: string | undefined;
};

export type UpdateRoomConfigResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace UpdateRoomConfigRequest$ {
    export type Inbound = {
        UpdateRoomConfigParams: UpdateRoomConfigParams$.Inbound;
        roomId: string;
        appId?: string | undefined;
    };

    export const inboundSchema: z.ZodType<UpdateRoomConfigRequest, z.ZodTypeDef, Inbound> = z
        .object({
            UpdateRoomConfigParams: UpdateRoomConfigParams$.inboundSchema,
            roomId: z.string(),
            appId: z.string().optional(),
        })
        .transform((v) => ({
            updateRoomConfigParams: v.UpdateRoomConfigParams,
            roomId: v.roomId,
            ...(v.appId === undefined ? null : { appId: v.appId }),
        }));

    export type Outbound = {
        UpdateRoomConfigParams: UpdateRoomConfigParams$.Outbound;
        roomId: string;
        appId?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateRoomConfigRequest> = z
        .object({
            updateRoomConfigParams: UpdateRoomConfigParams$.outboundSchema,
            roomId: z.string(),
            appId: z.string().optional(),
        })
        .transform((v) => ({
            UpdateRoomConfigParams: v.updateRoomConfigParams,
            roomId: v.roomId,
            ...(v.appId === undefined ? null : { appId: v.appId }),
        }));
}

/** @internal */
export namespace UpdateRoomConfigResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
    };

    export const inboundSchema: z.ZodType<UpdateRoomConfigResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => ({
            contentType: v.ContentType,
            statusCode: v.StatusCode,
            rawResponse: v.RawResponse,
        }));

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateRoomConfigResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => ({
            ContentType: v.contentType,
            StatusCode: v.statusCode,
            RawResponse: v.rawResponse,
        }));
}
